# config context path to "/" by setting an empty string
server:
  contextPath:

spring:
  # JACKSON
  jackson:
    serialization:
      INDENT_OUTPUT: true
  data:
    # MONGO DB
    mongodb:
      database: horaponto
      username: user8GL
      password: ***
      uri: mongodb://***:***@mongodb/horaponto

jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh

#logging:
#  level:
#    org.springframework:
#      security: DEBUG
